- hosts: localhost
  become: true
  tasks:
    - name: install group of programs
      yum:
       name: "{{ package }}"
      vars:
        package:
        - mc
        - wget
        - tar
        - bind-utils
        - net-tools
        - telnet
        - 
        
        state: latest
    
    - name: Install ansible.posix
      command: ansible-galaxy collection install ansible.posix

    - name: Install Python
      yum: name=python state=latest

    - name: install pip
      yum: name=python-pip state=latest

    - name: install Docker
      yum: name=docker state=latest

    - name: assicurati che docker sia attivo
      service:
        name: docker
        state: started
        enabled: yes

    - name: restart docker
      service:
        name: docker
        state: restarted

  
    - name: open 80 port
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: open 443 port
      ansible.posix.firewalld:
        service: https
        permanent: yes
        state: enabled
    - name: restart service firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted
        
    - name: Disable Root Login
      lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin no"
           state: present
           backup: yes
      become: yes
      notify:
        - restart ssh
  


  handlers:
     - name: restart ssh
       service:
         name: sshd
         state: restarted


