version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    networks:
    - jenkins-net
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./vol/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "./vol/nginx/ssl:/etc/nginx/ssl"
    - "./vol/nginx/html:/usr/share/nginx/html"
    
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
    - jenkins-net
    volumes:
    - "./vol/jenkins/home:/var/jenkins_home"

networks:
  jenkins-net:
