

version: "3"
services:
  db:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 1
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        max_failure_ratio: 0.3
    image: mysql:8.0.25
    privileged: true
    ports:
      - "30000:3306"
    networks:
      - appnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_practice_v3

  app:
    depends_on:
      - db
    deploy:
      replicas: 1
    image: nvynnyk/python-projectnzrb:2.0
    privileged: true
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet


networks:
  appnet:
    driver: overlay



