version: '3'

networks:
  default:
    external:
      name: network

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=admin@example.com

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
    - network
    volumes:
    - "./vol/jenkins/home:/var/jenkins_home"

volumes:
  certs:
  vhost.d:
  html: 